archiver_version: "master"
archiver_repo: "http://github.com/chrisseto/Archiver"

callback_addresses:
  - "http://192.168.111.111:7000/callback"
  - "http://192.168.111.1:5000/api/v1/registration/finished/"
foreman_port: 7000
ignore_callback_ssl: no
rabbitmq_url: "amqp://archiver:archiver@localhost//"
virtualenv_path: /env/archiver
archiver_install_path: /opt/app/Archiver/
s3_access_key:
s3_secret_key:
s3_bucket:
figshare_client_id:
figshare_client_secret:

## Directory Options ##
files_directory: Files/
manifest_directory: Manifests/
metadata_directory: File Metadata/
dirstruct_directory: Directory Structures/
parity_directory: Parities/
