- name: Ensure system dependencies
  sudo: yes
  apt:
    state: present
    pkg: "{{ item }}"
  with_items:
    - "ntp"
    - "python-pip"


- name: Ensure pip dependencies
  sudo: yes
  pip:
    state: present
    name: "{{ item }}"
  with_items:
    - "docker-py"
    - "python-apt"


- name: Ensure docker apt keys
  sudo: yes
  apt_key:
    id: 36A1D7869245C8950F966E92D8576A8BA88D21E9
    keyserver: "hkp://keyserver.ubuntu.com:80"
    state: present


- name: Ensure docker apt repositories
  sudo: yes
  apt_repository:
    repo: "deb https://get.docker.com/ubuntu docker main"
    state: present


- name: Ensure docker
  sudo: yes
  apt:
    state: present
    pkg: "lxc-docker"


- name: Ensure waterbutler directories exist
  sudo: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ waterbutler_config_dir }}"
    - "{{ waterbutler_redis_dir }}"
    - "{{ waterbutler_rabbitmq_dir }}"
    - "{{ waterbutler_osfstorage_pending_dir }}"
    - "{{ waterbutler_osfstorage_complete_dir }}"
  tags:
    - update
    - settings


- name: Copy newrelic settings
  template:
    mode: 0776
    src: newrelic.ini.j2
    dest: "{{ waterbutler_config_dir }}/newrelic.ini"
  tags:
    - update
    - settings


- name: Copy waterbutler settings
  copy:
    dest: "{{ waterbutler_config_dir }}/waterbutler-{{ waterbutler_env }}.json"
    src: "~/.cos/waterbutler-{{ waterbutler_env }}.json"
    mode: 0776
  tags:
    - update
    - settings


- name: Delete docker containers
  sudo: yes
  shell: "docker rm -f $(docker ps -aq)"
  ignore_errors: yes
  tags:
    - clean


- name: Delete docker images
  sudo: yes
  shell: "docker rmi -f $(docker images -q)"
  ignore_errors: yes
  tags:
    - clean


- name: Run Redis image
  docker:
    image: "redis:latest"
    restart_policy: always
    name: waterbutler_redis_1
    volumes:
      - "{{ waterbutler_redis_dir }}:/data"
  tags:
    - update


- name: Run RabbitMQ image
  docker:
    restart_policy: always
    name: waterbutler_rabbitmq_1
    hostname: waterbutler_rabbitmq_1
    image: "centerforopenscience/rabbitmq:latest"
    volumes:
      - "{{ waterbutler_rabbitmq_dir }}:/var/lib/rabbitmq"
  tags:
    - update


- name: Run WaterButler Server image
  docker:
    name: "waterbutler_server_{{ item }}"
    image: "centerforopenscience/waterbutler:latest"
    command: newrelic-admin run-program invoke server
    # expose:
    #   - "{{ (waterbutler_start_port | int) + (item | int) }}"
    ports:
      - "{{ (waterbutler_start_port | int) + (item | int) - 1 }}:7777"
    env:
      ENV: "{{ waterbutler_env }}"
      NEW_RELIC_CONFIG_FILE: /newrelic.ini
    links:
      - waterbutler_redis_1:redis
      - waterbutler_rabbitmq_1:rabbitmq
    restart_policy: always
    volumes:
      - "{{ waterbutler_osfstorage_pending_dir }}:/data/osfstorage/pending"
      - "{{ waterbutler_osfstorage_complete_dir }}:/data/osfstorage/complete"
      - "{{ waterbutler_config_dir }}/waterbutler-{{ waterbutler_env }}.json:/home/python/.cos/waterbutler-{{ waterbutler_env }}.json:ro"
      - "{{ waterbutler_config_dir }}/newrelic.ini:/newrelic.ini:ro"
  tags:
    - update
  with_sequence: "{{ waterbutler_instances }}"


- name: Run WaterButler Celery image
  docker:
    name: waterbutler_celery_1
    image: "centerforopenscience/waterbutler:latest"
    command: newrelic-admin run-program invoke celery
    restart_policy: always
    env:
      ENV: "{{ waterbutler_env }}"
      NEW_RELIC_CONFIG_FILE: /newrelic.ini
    links:
      - waterbutler_redis_1:redis
      - waterbutler_rabbitmq_1:rabbitmq
    volumes:
      - "{{ waterbutler_osfstorage_pending_dir }}:/data/osfstorage/pending"
      - "{{ waterbutler_osfstorage_complete_dir }}:/data/osfstorage/complete"
      - "{{ waterbutler_config_dir }}/waterbutler-{{ waterbutler_env }}.json:/home/python/.cos/waterbutler-{{ waterbutler_env }}.json:ro"
      - "{{ waterbutler_config_dir }}/newrelic.ini:/newrelic.ini:ro"
  tags:
    - update


# - name: Run WaterButler Ambassadors
#   docker:
#     image: ctlc/ambassador
#     name: 'waterbutler_server_{{ item }}_amb'
#     expose:
#       - 7777
#     ports:
#       - "7777:7777"
#     links:
#       - 'waterbutler_server_{{ item }}'
#     restart_policy: always
#   tags:
#     - update
#   with_items:
#     - '1'
