- name: Ensure system dependencies
  apt:
    state: present
    pkg: "{{ item }}"
  with_items:
    - "par2"
    - "logrotate"
    - "python3-dev"
    - "redis-server"
    - "python-redis"


- name: Ensure apps directory
  file:
    path: "{{ waterbutler_apps_dir }}"
    state: directory
    owner: www-data
    group: waterbutler
    recurse: yes
    mode: 0775


- name: Ensure settings directory
  file:
    path: "{{ waterbutler_conf_dir }}"
    state: directory
    owner: www-data
    group: waterbutler
    recurse: yes
    mode: 0775


- name: Ensure log directory
  file:
    path: "{{ waterbutler_log_dir }}"
    state: directory
    owner: www-data
    group: waterbutler
    recurse: yes
    mode: 0775


- name: Ensure SSL directory
  file:
    path: "{{ waterbutler_ssl_dir }}"
    state: directory
    owner: www-data
    group: waterbutler
    mode: 0775
  when: waterbutler_ssl
  tags:
    - update


- name: Copy SSL certificate
  copy:
    src: "{{ waterbutler_ssl_cert_src }}"
    dest: "{{ waterbutler_ssl_cert }}"
  when: waterbutler_ssl
  tags:
    - update


- name: Copy SSL key
  copy:
    src: "{{ waterbutler_ssl_key_src }}"
    dest: "{{ waterbutler_ssl_key }}"
  when: waterbutler_ssl
  tags:
    - update


- name: Ensure venv directory
  file:
    path: "{{ waterbutler_venvs_dir }}"
    state: directory
    owner: www-data
    group: waterbutler
    mode: 0755


- name: Create venv
  command: "virtualenv -p python3 {{ waterbutler_venv }}"
  args:
    creates: "{{ waterbutler_venv }}"


- name: Allow www-data to bind to low ports
  capabilities:
    path: "{{ waterbutler_venv }}bin/python3"
    capability: cap_net_bind_service+ep
    state: present
  sudo: yes
  tags:
    - update


- name: Ensure file directories
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: waterbutler
    mode: 0755
  with_items:
    - "{{ waterbutler_file_path_pending }}"
    - "{{ waterbutler_file_path_complete }}"
  tags:
    - update


- name: Ensure invoke
  pip:
    name: invoke
    virtualenv: "{{ waterbutler_venv }}"


- name: Ensure www-data:upload ownership of venv
  file:
    path: "{{ waterbutler_venv }}"
    state: directory
    recurse: yes
    mode: 0775
    group: waterbutler
    owner: www-data


- name: Pull from GitHub
  git:
    repo: "https://github.com/CenterForOpenScience/waterbutler"
    dest: "{{ waterbutler_repo_dir }}"
    version: "{{ waterbutler_repo_branch }}"
    update: yes
  sudo: False
  tags:
    - update


- name: Install WaterButler
  command: "{{ waterbutler_venv }}bin/python3 setup.py develop"
  args:
    chdir: "{{ waterbutler_repo_dir }}"
  tags:
    - update


- name: Copy Settings
  template:
    src: waterbutler.conf.j2
    dest: "{{ waterbutler_conf_dir }}server.conf"
    owner: www-data
    group: waterbutler
    mode: 0755
  tags:
    - update
    - settings


- name: Ensure www-data:upload ownership of repo
  file:
    path: "{{ waterbutler_repo_dir }}"
    state: directory
    recurse: yes
    mode: 0775
    owner: www-data
    group: waterbutler


- name: Ensure Python requirements
  pip:
    requirements: "{{ waterbutler_repo_dir }}dev-requirements.txt"
    extra_args: "--upgrade"
    virtualenv: "{{ waterbutler_venv }}"
  tags:
    - update


- name: Ensure supervisor config for celery
  template:
    src: celery.conf.j2
    dest: /etc/supervisor/conf.d/celery.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - update


- name: Ensure supervisor config for tornado
  template:
    src: tornado.conf.j2
    dest: /etc/supervisor/conf.d/tornado.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - update


- name: Ensure logrotate config
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/waterbutler
    owner: root
    group: root
    mode: 0644
  tags:
    - update


- name: Ensure Redis is running
  service:
    name: redis-server
    state: started
    enabled: yes
  tags:
    - update


- name: Ensure Redis configuration
  redis:
    command: config
    name: maxmemory
    value: "{{ waterbutler_redis_maxmemory }}"
  tags:
    - update


- name: Ensure supervisor is running
  service:
    name: supervisor
    state: started
    enabled: yes
  tags:
    - update


# - name: Ensure celery
#   include: supervisor-restart.yml name=celery
#   tags:
#     - update


- name: Ensure tornado
  include: supervisor-restart.yml name=tornado
  tags:
    - update
    - settings
