- name: Install emacs
  apt:
    pkg: "{{editors_emacs_base}}"
    state: present
  when: i_use_emacs

- name: Make sure vim-tiny is uninstalled
  apt:
    pkg: "vim-tiny"
    state: absent
  when: i_use_vim


- name: Make sure your vim is installed
  apt:
    pkg: "{{editors_vim_base}}"
    state: present
  when: i_use_vim
