- name: Install emacs
  apt:
    pkg: "{{editors_emacs_base}}"
    state: present

- name: Make sure vim-tiny is uninstalled
  apt:
    pkg: "vim-tiny"
    state: absent


- name: Make sure your vim is installed
  apt:
    pkg: "{{editors_vim_base}}"
    state: present
