# Execute common roles
- name: Common Ubuntu setup
  hosts: all
  roles:
    - role: hostname
    # - role: network_interfaces
    - role: Ansibles.generic-users
    - role: Ansibles.timezone
    - role: ssh
    - role: apt
    - role: editors

