- name: Requirements
  apt: "pkg={{ item }} state=present update_cache=yes"
  sudo: yes
  with_items:
    - git
    - par2
    - python-dev
    - python-pip
    - libxml2-dev
    - libxslt1-dev
    - lib32z1-dev

- name: Ensure virtualenv
  pip:
    name: virtualenv
    state: present

- name: Create virtualenv
  command: "virtualenv {{ virtualenv_path }} creates={{ virtualenv_path }}/bin/python"

- name: "Make sure apps folder exists and is owned by www-data"
  file:
    path: "{{ archiver_install_path }}"
    state: directory
    recurse: yes
    mode: 0775
    owner: www-data

- name: Clone
  git:
    repo: "{{ archiver_repo}}"
    dest: "{{ archiver_install_path }}"
    version: "{{archiver_version}}"
  tags: update

- name: Python Requirements
  pip:
    virtualenv: "{{ virtualenv_path }}"
    requirements: "{{ archiver_install_path }}requirements.txt"
  tags: update

- name: Configuration
  template:
    src: local.py.j2
    dest: "{{ archiver_install_path }}archiver/settings/local.py"
  sudo: yes
  tags: update
