- name: Requirements
  apt: "pkg={{ item }} state=present"
  sudo: yes
  with_items:
    - par2
    - git
    - python-pip

- name: Clone
  git: "repo={{ archiver_repo}} dest=/Archiver/"

- name: Python Requirements
  pip: requirements=/Archiver/requirements.txt

- name: Configuration
  template: src=local.py.j2 dest=/Archiver/archiver/settings/local.py
