# file: roles/ssh/defaults/main.yml


# sshd_config settings
ssh_port: "22"
ssh_protocol: "2"

ssh_hostkeys:
  - /etc/ssh/ssh_host_rsa_key
  - /etc/ssh/ssh_host_dsa_key
  - /etc/ssh/ssh_host_ecdsa_key
  - /etc/ssh/ssh_host_ed25519_key

ssh_useprivilegeseparation: "yes"
ssh_keyregenerationinterval: "3600"
ssh_serverkeybits: "768"
ssh_syslogfacility: "AUTH"
ssh_loglevel: "INFO"
ssh_logingracetime: "120"
ssh_permitrootlogin: "no"
ssh_strictmodes: "yes"
ssh_rsaauthentication: "yes"
ssh_pubkeyauthentication: "yes"
ssh_rhostsrsaauthentication: "no"
ssh_hostbasedauthentication: "no"
ssh_challengeresponseauthentication: "no"
ssh_passwordauthentication: "no"
ssh_x11forwarding: "yes"
ssh_x11displayoffset: "10"
ssh_printmotd: "no"
ssh_printlastlog: "yes"
ssh_tcpkeepalive: "yes"
ssh_acceptenv: "LANG LC_*"
ssh_subsystem: "sftp /usr/lib/openssh/sftp-server"
ssh_usepam: "yes"
ssh_usedns: "no"
ssh_clientaliveinterval: "1750"
ssh_clientalivecountmax: "0"
ssh_ignorerhosts: "no"

# run tests
ssh_test: yes
# User for testing
ssh_test_user: vagrant
ssh_test_port: 2222
