- name: Create user
  user:
    name: "{{ foreman_user }}"
    createhome: no

- name: Create tornado log files directory
  file:
    path: /var/log/tornado/
    state: directory
    owner: "{{ foreman_user }}"

- name: Create SSL cert directory
  file:
    path: "{{ archiver_install_path }}certs/"
    state: directory
  tags:
    - update

- name: Copy SSL cert
  copy:
    src: archiver.crt
    dest: "{{ archiver_install_path }}certs/archiver.crt"
  tags:
    - update

- name: Copy SSL key
  copy:
    src: archiver.key.nopass
    dest: "{{ archiver_install_path }}certs/archiver.key.nopass"
  tags:
    - update

- name: Copy Nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/archiver.conf
  tags:
    - update

- name: Enable Archiver in nginx
  file:
    src: /etc/nginx/sites-available/archiver.conf
    dest: /etc/nginx/sites-enabled/archiver.conf
    state: link
  tags:
    - update

- name: Disable default nginx site
  file:
    path: /etc/nginx/sites-available/default
    state: absent
  sudo: yes

- name: Add to Supervisor
  template:
    src: archiverforeman.conf.j2
    dest: /etc/supervisor/conf.d/archiverforeman.conf
    owner: root
    group: root
    mode: 0644
  tags: update

- name: Reload Supervisor
  supervisorctl:
    name: archiverforeman
    state: present

- name: Start foreman
  supervisorctl:
    name: archiverforeman
    state: started
  register: foreman_started
  ignore_errors: true
  tags: update

- name: Restart foreman
  supervisorctl:
    name: archiverforeman
    state: restarted
  tags: update
  when: 'foreman_started|failed'

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
  tags: update
