- name: Check if managed by Supervisor
  supervisorctl: name=celeryd state=present
  register: celery_is_managed
  ignore_errors: true

- name: Add to Supervisor
  template:
    src: celeryd.conf.j2
    dest: /etc/supervisor/conf.d/celeryd.conf
    owner: root
    group: root
    mode: 0644
  when: 'celery_is_managed|failed'

- name: Reload Supervisor
  supervisorctl:
    name: celeryd
    state: present

- name: Start worker
  supervisorctl:
    name: celeryd
    state: restarted
