- name: Create log files directory
  file:
    path: /var/log/archiver/
    state: directory
    mode: 0777

- name: Create log files
  file:
    path: /var/log/archiver/worker.log
    state: touch
    mode: 0777

- name: Add to Supervisor
  template:
    src: celeryd.conf.j2
    dest: /etc/supervisor/conf.d/celeryd.conf
    owner: root
    group: root
    mode: 0644
  tags: update

- name: Reload Supervisor
  supervisorctl:
    name: celeryd
    state: present
  tags: update

- name: Restart worker
  supervisorctl:
    name: celeryd
    state: restarted
  ignore_errors: true
  register: worker_restarted
  tags: update

- name: Start worker
  supervisorctl:
    name: celeryd
    state: started
  when: 'worker_restarted|failed'
  tags: update
