# file: timezone/tasks/main.yml

- name: ntp | timezone | Make sure tzdata is installed
  apt:
    pkg: tzdata
    state: present

- name: ntp | timezone | Update the hardware clock
  command: dpkg-reconfigure -f noninteractive tzdata
