- name: Ensure Redis is installed
  apt:
    state: present
    pkg: "{{ item }}"
  with_items:
    - "redis-server"
    - "python-redis"


- name: Ensure apps directory
  file:
    path: "{{ uploader_apps_dir }}"
    state: directory
    owner: www-data
    group: upload-worker
    recurse: yes
    mode: 0775


- name: Ensure log directory
  file:
    path: "{{ uploader_log_dir }}"
    state: directory
    owner: www-data
    group: upload-worker
    recurse: yes
    mode: 0775


- name: Ensure venv directory
  file:
    path: "{{ uploader_venvs_dir }}"
    state: directory
    owner: www-data
    group: upload-worker
    mode: 0755


- name: Create venv
  command: "virtualenv {{ uploader_venvs_dir }}upload"
  args:
    creates: "{{ uploader_venvs_dir }}upload/bin/python"


- name: Ensure invoke
  pip:
    name: invoke
    virtualenv: "{{ uploader_venv }}"


- name: Ensure www-data:upload ownership of venv
  file:
    path: "{{ uploader_venv }}"
    state: directory
    recurse: yes
    mode: 0775
    group: upload-worker
    owner: www-data


- name: Pull from GitHub
  git:
    repo: "https://github.com/CenterForOpenScience/osf-upload-service"
    dest: "{{ uploader_repo_dir }}"
    version: "{{ uploader_repo_branch }}"
    update: yes
  sudo: False
  tags:
    - update


- name: Copy local.py file
  template:
    src: local.py.j2
    dest: "{{ uploader_repo_dir }}cloudstorm/settings/local.py"
    owner: www-data
    group: upload-worker
    mode: 0755
  tags:
    - update


- name: Ensure www-data:upload ownership of repo
  file:
    path: "{{ uploader_repo_dir }}"
    state: directory
    recurse: yes
    mode: 0775
    owner: www-data
    group: upload-worker


- name: Ensure Python requirements
  pip:
    requirements: "{{ uploader_repo_dir }}dev-requirements.txt"
    extra_args: "--upgrade"
    virtualenv: "{{ uploader_venv }}"
  tags:
    - update


- name: Ensure supervisor config for celery
  template:
    src: celery.conf.j2
    dest: /etc/supervisor/conf.d/celery.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - update


- name: Ensure supervisor config for tornado
  template:
    src: tornado.conf.j2
    dest: /etc/supervisor/conf.d/tornado.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - update


- name: Ensure Redis is running
  service:
    name: redis-server
    state: started
    enabled: yes
  tags:
    - update


- name: Ensure Redis configuration
  redis:
    command: config
    name: maxmemory
    value: "{{ uploader_redis_maxmemory }}"
  tags:
    - update


- name: Ensure supervisor is running
  service:
    name: supervisor
    state: started
    enabled: yes
  tags:
    - update


- name: Ensure celery
  include: supervisor-restart.yml name=celery
  tags:
    - update


- name: Ensure tornado
  include: supervisor-restart.yml name="tornado"
  tags:
    - update
