- name: Ensure system dependencies
  sudo: yes
  apt:
    state: present
    pkg: python-pip


- name: Ensure pip dependencies
  sudo: yes
  pip:
    state: present
    name: "{{ item }}"
  with_items:
    - "docker-py"
    - "python-apt"


- name: Ensure docker apt keys
  sudo: yes
  apt_key:
    id: 36A1D7869245C8950F966E92D8576A8BA88D21E9
    keyserver: "hkp://keyserver.ubuntu.com:80"
    state: present


- name: Ensure docker apt repository
  sudo: yes
  apt_repository:
    repo: "deb https://get.docker.com/ubuntu docker main"
    state: present


- name: Ensure docker
  sudo: yes
  apt:
    state: present
    pkg: "lxc-docker"

