- name: Ensure system dependencies
  sudo: yes
  apt:
    state: present
    pkg: "{{ item }}"
  with_items:
    - "python-pip"
    - "logrotate"


- name: Ensure pip dependencies
  sudo: yes
  pip:
    state: present
    name: "{{ item }}"
  with_items:
    - "docker-py"
    - "python-apt"


- name: Ensure apt keys
  sudo: yes
  apt_key:
    id: 36A1D7869245C8950F966E92D8576A8BA88D21E9
    keyserver: "hkp://keyserver.ubuntu.com:80"
    state: present


- name: Ensure apt repositories
  sudo: yes
  apt_repository:
    repo: "deb https://get.docker.com/ubuntu docker main"
    state: present


- name: Ensure Docker
  sudo: yes
  apt:
    state: present
    pkg: "lxc-docker"

- name: Make settings directory
  file:
    state: directory
    path: "{{ haproxy_config_dir }}"

- name: Copy settings
  template:
    mode: 0776
    src: "haproxy.conf"
    dest: "{{ haproxy_config_dir }}/haproxy.cfg"


- name: Clean up old dockers
  docker:
    image: "{{ item }}"
    state: absent
  with_items:
    - "ctlc/ambassador"
    - "centerforopenscience/haproxy:latest"
  tags:
    - update


- name: Run WaterButler Ambassadors
  docker:
    image: ctlc/ambassador
    name: 'waterbutler_server_{{ item }}_amb'
    expose:
      - 7777
    env:
      "REMOTE_PORT_7777_TCP": "tcp://192.168.111.11{{ item }}:7777"
    restart_policy: always
  tags:
    - update
  with_items:
    - '1'
    - '2'

- name: Run HAProxy
  docker:
    name: 'haproxy_1'
    image: 'centerforopenscience/haproxy:latest'
    expose:
      - 80
      - 443
    ports:
      - '80:80'
      - '443:443'
    links:
      - 'waterbutler_server_1_amb:waterbutler1'
      - 'waterbutler_server_2_amb:waterbutler2'
    volumes:
    - '{{ haproxy_config_dir }}/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro'
    restart_policy: always
  tags:
    - update
