- name: Ensure directories exist
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ haproxy_config_dir }}"
    - "{{ haproxy_config_dir }}/ssl"
    - "{{ haproxy_config_dir }}/ssl/certs.d"
  tags:
    - update
    - settings


- name: Copy settings
  template:
    mode: 0755
    src: "haproxy.conf.j2"
    dest: "{{ haproxy_config_dir }}/haproxy.cfg"
  tags:
    - update


# - name: haproxy_default_cert_src
#   debug:
#     msg: "{{ haproxy_default_cert_src }}"


# - name: haproxy_default_cert_src
#   debug:
#     msg: "{{ haproxy_config_dir }}/ssl/default.pem"


- name: Copy SSL default certificate
  copy:
    mode: 0640
    src: "{{ haproxy_default_cert_src }}"
    dest: "{{ haproxy_config_dir }}/ssl/default.pem"
  tags:
    - update
  when: haproxy_default_cert_src | default("") != ""


- name: Copy SSL certificates directory
  copy:
    mode: 0640
    src: "{{ haproxy_certsd_dir_src }}"
    dest: "{{ haproxy_config_dir }}/ssl/certs.d"
  tags:
    - update
  when: haproxy_certsd_dir_src | default("") != ""


- name: Delete docker containers
  sudo: yes
  shell: "docker rm -f $(docker ps -aq)"
  ignore_errors: yes
  tags:
    - clean
    - clean_containers


- name: Delete docker images
  sudo: yes
  shell: "docker rmi -f $(docker images -q)"
  ignore_errors: yes
  tags:
    - clean
    - clean_images


- name: Run HAProxy
  docker:
    name: haproxy_1
    image: "centerforopenscience/haproxy:latest"
    expose:
      - 80
      - 443
    restart_policy: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "{{ haproxy_config_dir }}/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
      - "{{ haproxy_config_dir }}/ssl:/etc/ssl/private"
  tags:
    - update
