- name: Make settings directory
  file:
    state: directory
    path: "{{ haproxy_config_dir}}"


- name: Copy settings
  template:
    mode: 0755
    src: "haproxy.conf.j2"
    dest: "{{ haproxy_config_dir }}/haproxy.cfg"
  tags:
    - update


- name: Copy SSL default certificate
  copy:
    mode: 0640
    src: "{{ haproxy_default_cert_src }}"
    dest: "{{ haproxy_config_dir }}/ssl/default.pem"
  tags:
    - update
  when: haproxy_default_cert_src


- name: Copy SSL certificates directory
  copy:
    mode: 0640
    src: "{{ haproxy_certsd_dir_src }}"
    dest: "{{ haproxy_config_dir }}/ssl/certs.d"
  tags:
    - update
  when: haproxy_certsd_dir_src


- name: Clean up old dockers
  docker:
    image: "{{ item }}"
    state: absent
  with_items:
    - "centerforopenscience/haproxy:latest"
  tags:
    - update


- name: Run HAProxy
  docker:
    name: haproxy_1
    image: "centerforopenscience/haproxy:latest"
    expose:
      - 80
      - 443
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "{{ haproxy_config_dir }}/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
      - "{{ haproxy_config_dir }}/ssl:/etc/ssl/private:ro"
    restart_policy: always
  tags:
    - update
