- name: Make settings directory
  file:
    state: directory
    path: "{{ haproxy_config_dir }}"


- name: Copy settings
  template:
    mode: 0755
    src: "haproxy.conf.j2"
    dest: "{{ haproxy_config_dir }}/haproxy.cfg"
  tags:
    - update

- name: Copy SSL cert
  copy:
    mode: 0755
    src: waterbutler.pem
    dest: "{{ haproxy_config_dir }}/waterbutler.pem"
  tags:
    - update
  when: haproxy_enable_https


- name: Clean up old dockers
  docker:
    image: "{{ item }}"
    state: absent
  with_items:
    # - "ctlc/ambassador"
    - "centerforopenscience/haproxy:latest"
  tags:
    - update


- name: Run HAProxy
  docker:
    name: 'haproxy_1'
    image: 'centerforopenscience/haproxy:latest'
    expose:
      - 80
      - 443
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '{{ haproxy_config_dir }}/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro'
      - '{{ haproxy_config_dir }}/waterbutler.pem:/etc/ssl/private/waterbutler.pem:ro'
    restart_policy: always
  tags:
    - update
