- name: Install csf upstart
  sudo: yes
  copy:
    src: csf-started
    dest: /etc/init/csf-started.conf
    mode: 0644


- name: Update csf system V
  sudo: yes
  copy:
    src: csf-started.d
    dest: /etc/init.d/csf-started
    mode: 0755


- name: Update upstart
  sudo: yes
  command: update-rc.d csf-started defaults


- name: restart machine
  command: shutdown -r now "Restart Docker and csf"
  async: 0
  poll: 0
  ignore_errors: true


- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }}
                state=started
  sudo: false
